BEGIN EXECUTE IMMEDIATE 'DROP TABLE auditoria_operacoes PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/ 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE fact_saldos PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/ 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tb_ordem_servico PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/ 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tb_moto PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/ 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tb_cliente PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/ 
